import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import Navbar from '../components/Navbar';
import CountdownTimer from '../components/CountdownTimer';
import MetricCard from '../components/MetricCard';
import { api } from '../lib/api';
import { getUser } from '../lib/auth';
import type { Application } from '../types';
export default function Dashboard(){const user=getUser();const [apps,setApps]=useState<Application[]>([]);useEffect(()=>{api.get('/applications').then(r=>setApps(r.data)).catch(()=>setApps([]));},[]);const reviewed=apps.filter(a=>a.aiScore!=null);const avg=reviewed.length?Math.round(reviewed.reduce((s,a)=>s+(a.aiScore||0),0)/reviewed.length):0;return <><Navbar/><main className="mx-auto max-w-7xl px-6 py-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-cyan-400">Candidate command center</p><h1 className="mt-1 text-4xl font-bold">Good to see you.</h1><p className="mt-2 text-slate-400">{user?.email} · {user?.candidateProfile?.visaStatus || 'Visa profile pending'}</p></div><Link to="/jobs" className="btn-primary inline-flex items-center justify-center">Explore sponsored roles <ArrowRight size={17} className="ml-2"/></Link></div><div className="mt-8 grid gap-4 md:grid-cols-4"><MetricCard label="Applications" value={apps.length} hint="Tracked in your workspace"/><MetricCard label="AI reviewed" value={reviewed.length} hint="Contextual match analyses"/><MetricCard label="Average match" value={reviewed.length?`${avg}/100`:'—'} hint="Across analyzed applications"/><MetricCard label="Review queue" value={apps.filter(a=>a.status==='REVIEW').length} hint="Applications needing action"/></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><CountdownTimer deadline={user?.candidateProfile?.visaClockDeadline}/><section className="panel p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-400"/><div><h2 className="font-semibold">Sponsorship transparency</h2><p className="text-sm text-slate-400">Verified sponsor signals are shown directly on job cards.</p></div></div><ul className="mt-5 space-y-3 text-sm text-slate-300"><li>• Company-level verified sponsor indicator</li><li>• Job-level sponsorship track</li><li>• AI feedback separates skill fit from immigration assumptions</li></ul></section></div><section className="mt-6 panel p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent applications</h2><Link to="/jobs" className="text-sm text-cyan-400">Find more roles</Link></div>{apps.length===0?<p className="mt-6 text-slate-500">No applications yet. Start from the job board.</p>:<div className="mt-5 divide-y divide-slate-800">{apps.slice(0,6).map(a=><Link key={a.id} to={`/applications/${a.id}`} className="flex items-center justify-between gap-4 py-4 hover:bg-slate-900/40"><div><p className="font-medium">{a.job.title}</p><p className="text-sm text-slate-500">{a.job.company.name}</p></div><div className="text-right"><p className="font-semibold">{a.aiScore!=null?`${a.aiScore}/100`:'Not analyzed'}</p><p className="text-xs text-slate-500">{a.status}</p></div></Link>)}</div>}</section></main></>}
